const Pubs = [
  {
    id: 1,
    imageSrc: "../Images/An-Pucan.jpg",
    title: "An Púcán",
    address: "11 Forster Street, Galway City, Ireland ",
    instagramLink: "https://www.instagram.com/anpucan/",
    websiteLink: "https://anpucan.ie/ ",
    phoneNumber: " +353 91 376 561",
    email: "info@anpucan.ie",
    about: "About An Púcán",
    AboutParagraph:
      "An Púcán is a traditional Irish pub located in the heart of Galway City, just a stone's throw from Eyre Square. It's a favorite spot for locals and tourists alike, with a lively atmosphere, great music, and a wide range of drinks and food. Whether you're looking for a quiet pint, a night out with friends, or some live music, An Púcán is the place to be.",
    PucanOverallRating: "4.5",
    user1: "John Doe",
    comment1: "This is a great pub! I highly recommend it.",
  },
  {
    id: 2,
    imageSrc: "../Images/Cookes-Thatch-Bar.jpg",
    title: "Cookes Thatch Bar",
    address: "2 Newcastle road, Galway City, Ireland,",
    instagramLink: "https://www.instagram.com/cookes_food/",
    websiteLink: "https://www.facebook.com/cookesgalway/",
    phoneNumber: " +353 91 521749",
    email: "info@anpucan.ie",
    about: "About Cookes Thatch Bar",
    AboutParagraph:
      "Cookes Thatch Bar is one of Galway’s oldest pubs. We are located in the West end of Galway City a 5 minute walk from the centre of the City. Cookes has been welcoming customers through its doors for hundreds of years.",
    PucanOverallRating: "4.5",
    user1: "John Doe",
    comment1: "This is a great pub! I highly recommend it.",
  },
  {
    id: 3,
    imageSrc: "../Images/Taylors-Bar.jpg",
    title: "Taylors Bar and Beer Garden",
    address: "7 Dominick Street Upper, Galway City, Ireland",
    instagramLink: "TaylorsGalway",
    websiteLink: "https://taylorsgalway.ie/",
    phoneNumber: " +353 91 450 475",
  },
  {
    id: 4,
    imageSrc: "../Images/Busker-Brownes.jpg",
    title: "Busker Brownes",
    address: "3-5 Cross Street Upper, Galway City, Ireland",
    instagramLink: "https://www.instagram.com/buskerbrownes.kirbysrestaurant/",
    websiteLink: "https://www.buskerbrownes.com/",
    phoneNumber: " +353 91 563 377",
  },
  {
    id: 5,
    imageSrc: "../Images/Front-Door.jpg",
    title: "The Front Door",
    address: "8 Cross Street & High Street, Galway City, Ireland",
    instagramLink: "https://www.instagram.com/frontdoorpub/",
    websiteLink: "https://www.frontdoorpub.com/",
    phoneNumber: " +353 91 563 757",
  },
  {
    id: 6,
    imageSrc: "../Images/McGettigans.jpg",
    title: "McGettigan's",
    address: "9-11 Prospect Hill, Eyre Square, Galway City, Ireland",
    instagramLink: "https://www.instagram.com/mcggalway/",
    websiteLink: "https://www.mcgettigans.com/galway-ireland.html",
    phoneNumber: " +353 91 331 010 ",
  },
  {
    id: 7,
    imageSrc: "../Images/Taaffes.jpg",
    title: "Taaffes",
    address: "19 Shop Street, Galway City, Ireland",
    instagramLink: "https://www.instagram.com/taaffesbar/",
    websiteLink: "https://taaffesbar.ie/",
    phoneNumber: " +353 91 564 066",
  },
  {
    id: 8,
    imageSrc: "../Images/Tig-Coili.jpg",
    title: "Tig Cóilí",
    address: "Tig Cóilí, Mainguard Street, Galway City, Ireland",
    instagramLink: "https://www.instagram.com/tigchoili/",
    websiteLink: "https://tigchoiligalway.com/",
    phoneNumber: " +353 91 561 294",
  },
  {
    id: 9,
    imageSrc: "../Images/Kings-Head.jpg",
    title: "The Kings Head",
    address: "15 High Street, Galway City, Ireland",
    instagramLink: "https://www.instagram.com/thekingsheadgalway/",
    websiteLink: "https://www.thekingshead.ie/",
    phoneNumber: " +353 91 566 630",
  },
  {
    id: 10,
    imageSrc: "../Images/Seven.jpg",
    title: "Seven Bar And Restaurant",
    address: "5-7 Bridge Street, Galway City, Ireland",
    instagramLink: "https://www.instagram.com/sevengalway/",
    websiteLink: "http://sevenbridgestreet.ie/",
    phoneNumber: " +353 91 563 804",
  },
  {
    id: 11,
    imageSrc: "../Images/Freeneys.jpg",
    title: "Freeneys",
    address: "19 High Street, Galway City, Ireland",
    instagramLink:
      "https://www.facebook.com/pages/Freeneys-Bar/172385122797626/",
    websiteLink: "https://www.galwaycitypubguide.com/freeneys.html",
    phoneNumber: " +353 91 562 609",
  },
  {
    id: 12,
    imageSrc: "../Images/Sliding-Rock.jpg",
    title: "Sliding Rock",
    address: "37 NewCastle Road, Galway City, Ireland",
    instagramLink: "https://www.facebook.com/theslidingrock/",
    websiteLink: "https://www.theslidingrock.ie/",
    phoneNumber: " +353 91 722 131",
  },
];

export default Pubs;
