const Pubs = [
    {
        imageSrc: "../Images/An-Pucan.jpg",
        title: "An Púcán",
        address: "11 Forster Street, Galway City, Ireland ",
        instagramLink: "https://www.instagram.com/anpucan/",
        websiteLink: "https://anpucan.ie/ ",
        phoneNumber: "Phone: +353 91 376 561",
    },
    {
        imageSrc: "../Images/Cookes-Thatch-Bar.jpg",
        title: "Cookes Thatch Bar",
        address: "2 Newcastle road, Galway City, Ireland,",
        instagramLink: "https://www.instagram.com/cookes_food/",
        websiteLink: "https://www.face  book.com/cookesgalway/",
        phoneNumber: "Phone: +353 91 521749",
    },
    {
        imageSrc: "../Images/Taylors-Bar.jpg",
        title: "Taylors Bar and Beer Garden",
        address: "7 Dominick Street Upper, Galway City, Ireland",
        instagramLink: "TaylorsGalway",
        websiteLink: "https://taylorsgalway.ie/",
        phoneNumber: "Phone: +353 91 450 475",
    },
    {
        imageSrc: "../Images/Busker-Brownes.jpg",
        title: "Busker Brownes",
        address: "3-5 Cross Street Upper, Galway City, Ireland",
        instagramLink: "https://www.instagram.com/buskerbrownes.kirbysrestaurant/",
        websiteLink: "https://www.buskerbrownes.com/",
        phoneNumber: "Phone: +353 91 563 377",
    },
    {
        imageSrc: "../Images/Front-Door.jpg",
        title: "The Front Door",
        address: "8 Cross Street & High Street, Galway City, Ireland",
        instagramLink: "https://www.instagram.com/frontdoorpub/",
        websiteLink: "https://www.frontdoorpub.com/",
        phoneNumber: "Phone: +353 91 563 757",
    },
    {
        imageSrc: "../Images/McGettigans.jpg",
        title: "McGettigan's",
        address: "9-11 Prospect Hill, Eyre Square, Galway City, Ireland",
        instagramLink: "https://www.instagram.com/mcggalway/",
        websiteLink: "https://www.mcgettigans.com/galway-ireland.html",
        phoneNumber: "Phone: +353 91 331 010 ",
    },  
    {
        imageSrc: "../Images/Taaffes.jpg",
        title: "Taaffes",
        address: "19 Shop Street, Galway City, Ireland",
        instagramLink: "https://www.instagram.com/taaffesbar/",
        websiteLink: "https://taaffesbar.ie/",
        phoneNumber: "Phone: +353 91 564 066",
    }, 
    {
        imageSrc: "../Images/Tig-Coili.jpg",
        title: "Tig Cóilí",
        address: "Tig Cóilí, Mainguard Street, Galway City, Ireland",
        instagramLink: "https://www.instagram.com/tigchoili/",
        websiteLink: "https://tigchoiligalway.com/",
        phoneNumber: "Phone: +353 91 561 294",
    },
    {
        imageSrc: "../Images/Kings-Head.jpg",
        title: "The Kings Head",
        address: "15 High Street, Galway City, Ireland",
        instagramLink: "https://www.instagram.com/thekingsheadgalway/",
        websiteLink: "https://www.thekingshead.ie/",
        phoneNumber: "Phone: +353 91 566 630",
    },
    {
        imageSrc: "../Images/Seven.jpg",
        title: "Seven Bar And Restaurant",
        address: "5-7 Bridge Street, Galway City, Ireland",
        instagramLink: "https://www.instagram.com/sevengalway/",
        websiteLink: "http://sevenbridgestreet.ie/",
        phoneNumber: "Phone: +353 91 563 804",
    },
    {
        imageSrc: "../Images/Freeneys.jpg",
        title: "Freeneys",
        address: "19 High Street, Galway City, Ireland",
        instagramLink: "https://www.facebook.com/pages/Freeneys-Bar/172385122797626/",
        websiteLink: "https://www.galwaycitypubguide.com/freeneys.html",
        phoneNumber: "Phone: +353 91 562 609",
    },
    {
        imageSrc: "../Images/Sliding-Rock.jpg",
        title: "Sliding Rock",
        address: "37 NewCastle Road, Galway City, Ireland",
        instagramLink: "https://www.facebook.com/theslidingrock/",
        websiteLink: "https://www.theslidingrock.ie/",
        phoneNumber: "Phone: +353 91 722 131",
    },
]

export default Pubs